name: Parcel Composer Release

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    name: Build java image
    permissions:
        packages: write
        contents: read

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: "alexgenon"

    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v1
          with:
            java-version: 17

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build JVM based image
          run: ./gradlew build

        - name: Build and push the JVM docker image
          uses: docker/build-push-action@v3
          with:
            push: true
            context: .
            file: src/main/docker/Dockerfile.jvm
            tags: |
              ghcr.io/alexgenon/parcel-composer:${{ github.ref_name }}
              ghcr.io/alexgenon/parcel-composer:latest

        - name: Build native
          run: ./gradlew build -Dquarkus.package.type=native

        - name: Build and push the native docker image
          uses: docker/build-push-action@v3
          with:
            push: true
            context: .
            file: src/main/docker/Dockerfile.native-micro
            tags: |
              ghcr.io/alexgenon/parcel-composer:native-${{ github.ref_name }}
              ghcr.io/alexgenon/parcel-composer:native-latest
